### ISSUE TITLE
Translation updates from Weblate

### ISSUE THREAD

**Issue by ACherepkov1989** [immersive-translate/immersive-translate#3247]
### 您希望的更新和改进是什么 | Update or Improve

When will the translation ([ru](https://weblate.immersivetranslate.com/projects/immersive-translate/extension/ru/)) from the Weblate repository be updated in the extension?

**Comment by keyboard3** [comment]
1.21.1 will support

**Comment by ACherepkov1989** [comment]
@keyboard3 , thank you.

As I understand it, there is a [conflict](https://weblate.immersivetranslate.com/projects/immersive-translate/extension/#history) between the GitHub and Weblate repositories when merging. Because of this, new data is not synchronized between repositories.

![Image](https://github.com/user-attachments/assets/69450cab-5ec0-4df2-88ef-5edcf04e5f8c)

**Comment by keyboard3** [comment]
This conflict should have been resolved by@owen

**Comment by keyboard3** [comment]
Sorry, this change has been reverted because it involved multiple i18n fields that should not be modified.  
When performing translation updates, please use the `en` language file as a reference and only modify the corresponding target language file. Do not directly change the `en` file, otherwise the changes will be synchronized to all other language files, causing unnecessary impact.

**Comment by ACherepkov1989** [comment]
An update was released today, and as far as I can see, the problem still persists during syncing.
Also, many rows weren't syncing with the current Weblate database.

**Comment by ACherepkov1989** [comment]
Hello, @theowenyoung and @keyboard3 .
The database has not been synchronized for over a month due to some conflicts during synchronization. Will the problem that appears almost every time be solved?

As I noticed, the Weblate service does not correctly synchronize data with the GitHub repository, and when you perform manual database synchronization with the resolution of conflicting lines, a partial synchronization of the database from Weblate to GitHub occurs. Because of this, when syncing from Weblate to GitHub, not all translations are copied, and sometimes the translation in Weblate is overwritten with outdated data from GitHub.

Please ensure that the data from Weblate has the highest priority when syncing the database.

**Comment by keyboard3** [comment]
Sorry for being busy recently and not following up promptly. I have scheduled a dedicated review of Weblate's overall synchronization process next week, focusing on confirming the cause of database conflicts, synchronization priorities, and data consistency from Weblate to GitHub, and ensuring that data on the Weblate side is handled with the highest priority. I will share the findings and follow-up plan as soon as the review is complete.

**Comment by ACherepkov1989** [comment]
Thank you for providing an answer and for continuing to look into the issue.

**Comment by ACherepkov1989** [comment]
Hello, @theowenyoung and @keyboard3 .
Will you be synchronizing the database from Weblate or has this already been abandoned?
